### ISSUE TITLE
[BC break] PJAX container selection

### ISSUE THREAD

**Issue by eborned** [phemellc/yii2-toggle-column#13]
I've been using this module for some time. But commit a043f481117b38a239f9ca8f1cac443677931cf5 broke the current implementation for me. My grids all have the grid-view class, but they don't have the data-pjax-container attribute.

Would it be possible to prevent these kind of breaking changes in the future? For example, by testing on the data attribute first and fall back to the original behavior.

 In the current setup, I have to add an identifier to each PJAX begin call and supply that to the gridview as a pjax-container.

**Comment by eborned** [comment]
I've added a pull request #14 to implement this fallback behavior

**Comment by arisk** [comment]
Hi,
Why do you need to add an identified to `Pjax::begin`? If you are using the Pjax widget you should always have a `data-pjax-container` attribute.

**Comment by eborned** [comment]
I see where this problem is coming from. I'm not running the latest Yii2 core, because that would take a lot of Q&A. I'm still on 2.0.6 from earlier this year.

The data-pjax-container attribute has been added in 2.0.7. I'll see if I can at least upgrade to that version.
Would it be possible to add a dependency for yii2 >= 2.0.7 in your composer.json? To prevent the same problem for others?

**Comment by arisk** [comment]
I added the dependency constraint. Thank you for taking the time to report this.
