### ISSUE TITLE
Primary key is not always an int

### ISSUE THREAD

**Issue by eborned** [phemellc/yii2-toggle-column#20]
The `ToggleAction` casts the `$id` attribute to an int. But a primary key is not required to be an int. I have a few use-cases where the primary key is some kind of unique identifier. This breaks the toggle action.

Is there a specific reason to cast the primary key?

**Comment by arisk** [comment]
I don't see a reason why it should be restricted to an integer. Can you create a pull request for this?

**Comment by eborned** [comment]
See #21
